spring.application.name=employee-service

spring.datasource.url=${DB_URL:jdbc}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# Enable Spring SQL initialization so schema.sql and data.sql in classpath are executed on startup
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.platform=postgres
spring.sql.init.continue-on-error=false

